export class Produto {
    constructor(
        public cc_fil?:string,
        public cc_psr?:string,
        public cc_psr_ccl?:string,
        public nm_psr?:string, 
        public cc_psr_cur?:string,
        public cc_pst?:string,
        public cc_psr_cfo?:string,
        public cc_psr_ori?:string,
        public cc_psr_ncm?:string, 
        public cc_psr_ces?:string,
        public cc_psr_cst_icm?:string,
        public pc_psr_ali_icm?:number, 
        public pc_psr_red_icm?:number,
        public cc_psr_cst_pis?:string,
        public pc_psr_ali_pis?:number, 
        public cc_psr_cst_cof?:string,
        public pc_psr_ali_cof?:number,
        public pc_psr_ali_ibt?:number,
        public cc_psr_gar?:string,
        public cc_psr_sg1?:string,
        public cc_psr_sg2?:string,
        public cc_psr_sg3?:string,
        public cc_psr_sg4?:string,
        public cc_psr_sg5?:string,
        public bl_psr_ean?: boolean,
        public bl_psr_sr1?: boolean,
        public bl_psr_sr2?: boolean,
        public qt_max_par?:number
    ){}
}
