export interface Filial {
      id_reg:any;
      cc_org:string;
      cc_fil:string;
      nm_fil:string;
      cc_ins_fed:string;
      st_fil:string;
      tx_end_log:string;
	  tx_end_num:string;
	  tx_end_cmp:string;
	  tx_end_bai:string;
	  cc_end_cpt:string;
	  cc_end_est:string;
	  cc_end_mun_cod:string;
	  tx_end_mun_nom:string;
	  cn_end_pai_cod:number;
	  tx_end_pai_nom:string;
	  tx_end_tel:string;
	  cc_ins_est:string;
	  cc_ins_mun:string;
	  cc_cna_fis:string;
	  cc_reg_tri:string;    
}